// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/elusiv0/oz_task/internal/dto"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Node   *dto.Comment `json:"node,omitempty"`
	Cursor int          `json:"cursor"`
}

type Mutation struct {
}

type PageInfo struct {
	StartCursor int   `json:"startCursor"`
	EndCursor   int   `json:"endCursor"`
	HasNextPage *bool `json:"hasNextPage,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *dto.Post `json:"node,omitempty"`
	Cursor int       `json:"cursor"`
}

type Query struct {
}

type Subscription struct {
}
